"""Generates Weekly_Briefing.md - a CEO-level summary of all activity."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from src.core.vault_manager import VaultManager


def generate_briefing(vault: VaultManager) -> Path:
    """Generate the weekly CEO briefing report."""
    counts = vault.get_status_counts()
    now = datetime.now(timezone.utc)
    week_str = now.strftime("%Y-W%W")

    # Collect data
    done_items = vault.list_items_recursive("Done")
    recent_done = done_items[-30:]
    needs_approval = vault.list_items_recursive("Needs_Approval")
    needs_action = vault.list_items_recursive("Needs_Action")

    lines = [
        f"# CEO Briefing - {week_str}",
        "",
        f"> Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "## Executive Summary",
        "",
        f"**Completed items:** {len(recent_done)}",
        f"**Pending action:** {counts.get('needs_action', 0)}",
        f"**Awaiting approval:** {counts.get('needs_approval', 0)}",
        f"**In progress:** {counts.get('in_progress', 0)}",
        "",
    ]

    # Items awaiting approval
    if needs_approval:
        lines.extend(["## Items Requiring Your Approval", ""])
        for path in needs_approval:
            try:
                task = vault.read_task(path)
                lines.append(
                    f"- **{task.title}** | Priority: {task.priority.value} | "
                    f"Action: {task.action_type} | [[{path.name}]]"
                )
            except Exception:
                lines.append(f"- [[{path.name}]]")
        lines.append("")

    # Completed items
    if recent_done:
        lines.extend(["## Recently Completed", ""])
        for path in recent_done:
            try:
                task = vault.read_task(path)
                lines.append(f"- [{task.source}] {task.title} - {task.result or 'completed'}")
            except Exception:
                lines.append(f"- {path.stem}")
        lines.append("")

    # Pending action items
    if needs_action:
        lines.extend(["## Pending Action Items", ""])
        for path in needs_action[:15]:
            try:
                task = vault.read_task(path)
                lines.append(f"- [{task.category}] {task.title} (priority: {task.priority.value})")
            except Exception:
                lines.append(f"- {path.stem}")
        lines.append("")

    lines.extend([
        "---",
        f"*Generated by Digital FTE CEO Briefing Agent | {now.strftime('%Y-%m-%d')}*",
    ])

    content = "\n".join(lines)
    return vault.write_raw(content, "Weekly_Briefing.md")
